export const surpriseMePrompts = [
    'A futuristic cityscape at night with flying cars and neon lights',
    'A majestic dragon soaring over a medieval castle',
    'A serene underwater scene with a sunken ship and colorful marine life',
    'A whimsical fairy forest with glowing mushrooms and tiny fairies',
    'A bustling alien marketplace on a distant planet',
    'A surreal desert landscape with floating islands and unusual rock formations',
    'A steampunk-inspired Victorian street with mechanical gadgets and airships',
    'A mysterious ancient temple hidden in a dense jungle',
    'A cozy, magical library filled with floating books and enchanted artifacts',
    'A towering robot standing guard over a futuristic city',
    'A breathtaking sunset over a tranquil mountain lake',
    'A playful group of mythical creatures having a tea party in a garden',
    'An astronaut exploring an alien world with strange plants and creatures',
    'A vibrant carnival scene with colorful tents and performers',
    'A majestic eagle flying over a rugged mountain range',
    'A whimsical hot air balloon festival in a picturesque countryside',
    'A grand, illuminated palace floating in the sky',
    'A charming, snowy village during the holiday season',
    'A fantastical landscape with giant, glowing crystals emerging from the ground',
    'A peaceful, ancient Japanese garden with cherry blossoms in full bloom',
    'A futuristic sports arena with holographic displays and high-tech gear',
    'A mystical cave filled with glowing stalactites and underground rivers',
    'A bustling harbor with tall ships and exotic goods being unloaded',
    'A serene moonlit beach with bioluminescent waves',
    'A towering ice castle in the midst of a frozen tundra',
    'A lively city square during a cultural festival',
    'A futuristic park with robotic animals and interactive art installations',
    'A surreal landscape with gravity-defying waterfalls and floating trees',
    'A vibrant rainforest teeming with exotic wildlife',
    'A cozy, rustic cabin in the woods during autumn',
    'A dazzling firework display over a serene lake',
    'A grand wizard’s tower filled with magical artifacts and spellbooks',
    'A futuristic space station orbiting a distant planet',
    'A serene, misty forest at dawn with rays of sunlight breaking through',
    'A lively street market in a colorful, historical city',
    'A majestic lion resting on a rock overlooking the savannah',
    'A whimsical garden with oversized flowers and insects',
    'A bustling café in a romantic, cobblestone street at sunset',
    'A futuristic metropolis with towering skyscrapers and advanced technology',
    'A serene river winding through a lush, green valley',
    'A grand ballroom filled with elegantly dressed dancers',
    'A mystical landscape with a glowing, magical portal',
    'A peaceful countryside with rolling hills and a quaint farmhouse',
    'A bustling marketplace in a futuristic city with holographic vendors',
    'A majestic whale swimming through an underwater city',
    'A serene temple garden with koi ponds and stone lanterns',
    'A futuristic laboratory with advanced robotic assistants',
    'A mysterious cave with ancient hieroglyphics and glowing crystals',
    'A lively beach scene with colorful umbrellas and surfers',
    'A futuristic city with flying cars and neon signs reflecting on rain-soaked streets',
    'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
];